# Generated by Django 5.2.4 on 2025-07-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
    ]
