# Generated by Django 5.2.4 on 2025-07-23 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_rename_fecha_comentario_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
