# Generated by Django 5.2.4 on 2025-07-23 23:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App1.categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_post/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
