# Generated by Django 5.2.4 on 2025-07-29 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_imagenpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpost',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imagenpost',
            name='imagen',
            field=models.ImageField(upload_to='galeria_post/'),
        ),
        migrations.AlterField(
            model_name='imagenpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='App1.post'),
        ),
    ]
