# Generated by Django 5.2.4 on 2025-07-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_alter_imagenpost_descripcion_alter_imagenpost_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpost',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
